export const A = {
  TITLE_SET: "TITLE_SET",

  /** Replace whole blocks array (internal convenience action used by advanced edits). */
  BLOCKS_REPLACE: "BLOCKS_REPLACE",

  BLOCK_INPUT: "BLOCK_INPUT",
  BLOCK_INSERT_AFTER: "BLOCK_INSERT_AFTER",
  BLOCK_CHANGE_TYPE: "BLOCK_CHANGE_TYPE",
  BLOCK_TOGGLE_TODO: "BLOCK_TOGGLE_TODO",
  BLOCK_DELETE_SELECTED: "BLOCK_DELETE_SELECTED",
  BLOCK_MERGE_WITH_PREV: "BLOCK_MERGE_WITH_PREV",

  FOCUS_SET: "FOCUS_SET",

  SELECT_BEGIN: "SELECT_BEGIN",
  SELECT_EXTEND_TO: "SELECT_EXTEND_TO",
  SELECT_END: "SELECT_END",
  SELECT_SET: "SELECT_SET",
  SELECT_CLEAR: "SELECT_CLEAR",

  DRAG_BEGIN: "DRAG_BEGIN",
  DRAG_OVER: "DRAG_OVER",
  DRAG_DROP: "DRAG_DROP",
  DRAG_END: "DRAG_END",

  SLASH_OPEN: "SLASH_OPEN",
  SLASH_QUERY: "SLASH_QUERY",
  SLASH_ACTIVE_SET: "SLASH_ACTIVE_SET",
  SLASH_ACTIVE_MOVE: "SLASH_ACTIVE_MOVE",
  SLASH_CLOSE: "SLASH_CLOSE",

  BLOCK_MENU_OPEN: "BLOCK_MENU_OPEN",
  BLOCK_MENU_QUERY: "BLOCK_MENU_QUERY",
  BLOCK_MENU_ACTIVE_SET: "BLOCK_MENU_ACTIVE_SET",
  BLOCK_MENU_ACTIVE_MOVE: "BLOCK_MENU_ACTIVE_MOVE",
  BLOCK_MENU_CLOSE: "BLOCK_MENU_CLOSE",
} as const;

export type EditorActionType = (typeof A)[keyof typeof A];
